language: python
sudo: false
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coverage codecov flake8

script:
  - coverage run main.py runtests
  - flake8 .

after_success:
  - codecov
